### ISSUE TITLE
Uncaught exception: 534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbuO6 #77

### ISSUE THREAD

**Issue by roroco** [nu7hatch/gmail#126]
This is error occurs in both gem 'ruby-gmail' and 'gmail', 

following is my code

```
require 'gmail'

gmail = Gmail.new("enormousoqecq@gmail.com", "uftkivqpfwfem")

gmail.deliver do
  to "email@example.com"
  subject "Having fun in Puerto Rico!"
  text_part do
    body "Text of plaintext message."
  end
  html_part do
    content_type 'text/html; charset=UTF-8'
    body "<p>Text of <em>html</em> message.</p>"
  end
  add_file "/path/to/some_image.jpg"
end
```
```
"534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbv9v "
Array (14 elements)
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/smtp.rb:969:in `check_auth_response'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/smtp.rb:740:in `auth_plain'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/smtp.rb:732:in `authenticate'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/smtp.rb:567:in `do_start'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/smtp.rb:520:in `start'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mail-2.6.1/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mail-2.6.1/lib/mail/message.rb:248:in `deliver!'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/gmail-0.4.2/lib/gmail/client/base.rb:130:in `deliver'"
"/home/roroco/Dropbox/rbs/ro_plans/ex/ex.rb:7:in `<top (required)>'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.4.24/lib/ruby-debug-ide.rb:86:in `debug_load'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.4.24/lib/ruby-debug-ide.rb:86:in `debug_program'"
"/home/roroco/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.4.24/bin/rdebug-ide:121:in `<top (required)>'"
"-e:1:in `load'"
"-e:1:in `<main>'"
```

**Comment by johnnyshields** [comment]
I've updated the readme with @jgrevich's answer. Closing issue.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#126

**Comment by Swati-Teks-30** [comment]
I have tried login with the browser and also UnlockCaptcha but still getting the same error. Any help ??

**Comment by ghost** [comment]
you have to just change gem 'ruby-gmail' to gem 'gmail' and it's work
